/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import BusinessLogic.DeleteUser;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class DonorsMainForm extends javax.swing.JFrame {

    private String lastDonation;
    String[] splitDate;
    private String nextDonation;

    private String getLastDonation() {
        return lastDonation;
    }

    private void setLastDonation(String lastDonation) {
        this.lastDonation = lastDonation;
    }

    /**
     * Creates new form DonorsMainForm
     */
    public DonorsMainForm() {
        initComponents();
        initiateComponents();

    }

    private void initiateComponents() {
        setLocation(200, 100);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../resources/icon.png")));
        lWarning.setText(null);
        BusinessLogic.fillDonorMainPage fillPage = new BusinessLogic.fillDonorMainPage();
        fillPage.fnGetLastDonationDate();
        setLastDonation(fillPage.getsLastDonationDate());
        lLastBloodDonation.setText("Your Last Blood donation was on : " + getLastDonation());
        if (getLastDonation().equals("'Never Before'")) {
            nextDonation = "Today";
        } else {
            splitDate = lastDonation.split("-");
            System.out.println(splitDate[0]);
            System.out.println(splitDate[1]);
            System.out.println(splitDate[2]);
            nextDonation = getNextDate();
        }
        lNextBloodDonation.setText("You may Donate Blood on : " + nextDonation);
        fillPage.fnGetNameOfTheUser();
        lWelcome.setText("Welcome, " + fillPage.getsNameOftheUser());

        fillPage.fnGetMgrName();
        if (fillPage.getBBName() != null && fillPage.getsNameOfTheMgr() != null) {
            lRegisteredWith.setText("You are registered with : " + fillPage.getBBName() + " ( " + fillPage.getsNameOfTheMgr() + ")");
        } else {
            lRegisteredWith.setText("You are registered with : Main Branch ");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lWelcome = new javax.swing.JLabel();
        OuterPanel = new javax.swing.JPanel();
        buttonpanel = new javax.swing.JPanel();
        bDonateBlood = new javax.swing.JButton();
        bViewProfile = new javax.swing.JButton();
        bDeleteAccount = new javax.swing.JButton();
        bDonateCash = new javax.swing.JButton();
        bSellBlood = new javax.swing.JButton();
        bRefresh = new javax.swing.JButton();
        innerPanel = new javax.swing.JPanel();
        lRegisteredWith = new javax.swing.JLabel();
        bRemindMe = new javax.swing.JButton();
        lNextBloodDonation = new javax.swing.JLabel();
        lLastBloodDonation = new javax.swing.JLabel();
        lWarning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Blood Bank - Registered User");
        setResizable(false);

        lWelcome.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        lWelcome.setText("Welcome, User");

        bDonateBlood.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        bDonateBlood.setText("Donate Blood");
        bDonateBlood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDonateBloodActionPerformed(evt);
            }
        });

        bViewProfile.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        bViewProfile.setText("View My profile");
        bViewProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bViewProfileActionPerformed(evt);
            }
        });

        bDeleteAccount.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        bDeleteAccount.setText("Delete Account");
        bDeleteAccount.setToolTipText("");
        bDeleteAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteAccountActionPerformed(evt);
            }
        });

        bDonateCash.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        bDonateCash.setText("Donate Cash");
        bDonateCash.setToolTipText("Provides information about Manager. You may donate cash to him and collect reciept");
        bDonateCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDonateCashActionPerformed(evt);
            }
        });

        bSellBlood.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        bSellBlood.setText("Be a Mediator");
        bSellBlood.setToolTipText("Provides information about Manager. You may donate cash to him and collect reciept");
        bSellBlood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSellBloodActionPerformed(evt);
            }
        });

        bRefresh.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        bRefresh.setText("Refresh/Extra");
        bRefresh.setToolTipText("Provides information about Manager. You may donate cash to him and collect reciept");
        bRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonpanelLayout = new javax.swing.GroupLayout(buttonpanel);
        buttonpanel.setLayout(buttonpanelLayout);
        buttonpanelLayout.setHorizontalGroup(
            buttonpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonpanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(buttonpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buttonpanelLayout.createSequentialGroup()
                        .addComponent(bDonateCash, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(bRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buttonpanelLayout.createSequentialGroup()
                        .addGroup(buttonpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bDonateBlood, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bViewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(buttonpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bDeleteAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bSellBlood, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
        );

        buttonpanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bDeleteAccount, bDonateBlood, bDonateCash, bViewProfile});

        buttonpanelLayout.setVerticalGroup(
            buttonpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bDonateBlood, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSellBlood, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(buttonpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bViewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bDeleteAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(buttonpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bDonateCash, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        buttonpanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bDeleteAccount, bDonateBlood, bDonateCash, bViewProfile});

        lRegisteredWith.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        lRegisteredWith.setText("You are registered with : ");

        bRemindMe.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        bRemindMe.setText("Remind me");
        bRemindMe.setToolTipText("This will send notification to the phone number");
        bRemindMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRemindMeActionPerformed(evt);
            }
        });

        lNextBloodDonation.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        lNextBloodDonation.setForeground(new java.awt.Color(0, 204, 0));
        lNextBloodDonation.setText("You may Donate Blood on : ");

        lLastBloodDonation.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        lLastBloodDonation.setForeground(new java.awt.Color(0, 204, 0));
        lLastBloodDonation.setText("Your Last Blood Donation was on :");

        javax.swing.GroupLayout innerPanelLayout = new javax.swing.GroupLayout(innerPanel);
        innerPanel.setLayout(innerPanelLayout);
        innerPanelLayout.setHorizontalGroup(
            innerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(innerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(innerPanelLayout.createSequentialGroup()
                        .addGroup(innerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lRegisteredWith)
                            .addComponent(lLastBloodDonation))
                        .addContainerGap(192, Short.MAX_VALUE))
                    .addGroup(innerPanelLayout.createSequentialGroup()
                        .addComponent(lNextBloodDonation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bRemindMe)
                        .addGap(36, 36, 36))))
        );
        innerPanelLayout.setVerticalGroup(
            innerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lLastBloodDonation)
                .addGap(18, 18, 18)
                .addGroup(innerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNextBloodDonation)
                    .addComponent(bRemindMe))
                .addGap(18, 18, 18)
                .addComponent(lRegisteredWith)
                .addContainerGap())
        );

        javax.swing.GroupLayout OuterPanelLayout = new javax.swing.GroupLayout(OuterPanel);
        OuterPanel.setLayout(OuterPanelLayout);
        OuterPanelLayout.setHorizontalGroup(
            OuterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OuterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OuterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(innerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        OuterPanelLayout.setVerticalGroup(
            OuterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OuterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(innerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(buttonpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lWarning.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        lWarning.setForeground(java.awt.Color.blue);
        lWarning.setText("lwarning");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(lWelcome)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lWarning)
                    .addComponent(OuterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lWelcome)
                .addGap(18, 18, 18)
                .addComponent(OuterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lWarning)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bRemindMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRemindMeActionPerformed
        JOptionPane.showConfirmDialog(this, "Notification Will be Sent to you on time", "Information", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_bRemindMeActionPerformed

    private void bDonateCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDonateCashActionPerformed
        JOptionPane.showConfirmDialog(this, "We do not have any online payment option.\nYou may pay manager directly", "Thank You", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_bDonateCashActionPerformed

    private void bDeleteAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteAccountActionPerformed
        int confirmation;
        confirmation = JOptionPane.showConfirmDialog(this, "Are you Sure ?", "Confirmation Dialog", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        System.out.println(confirmation);
        if (confirmation == 0) {
            BusinessLogic.DeleteUser deletednr = new DeleteUser();
            deletednr.deleteDonor();
            this.dispose();
        }
    }//GEN-LAST:event_bDeleteAccountActionPerformed

    private void bViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bViewProfileActionPerformed
        DonorUpdateform updateform = new DonorUpdateform();
        updateform.setVisible(true);
    }//GEN-LAST:event_bViewProfileActionPerformed

    private void bDonateBloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDonateBloodActionPerformed
        Object[] possibilities = {"A+", "B+", "O+", "AB+", "A-", "B-", "O-", "AB-"};
        String s = (String) JOptionPane.showInputDialog(
                this,
                "Select Blood Group\n",
                "Select Blood",
                JOptionPane.PLAIN_MESSAGE,
                null,
                possibilities,
                "Blood Groups");
        System.out.println(s);
        BusinessLogic.DonateBloodBL donate = new BusinessLogic.DonateBloodBL();
        donate.setBloodtype(s);
        donate.incrementBlood();
        lWarning.setText("Blood donation is registered");
    }//GEN-LAST:event_bDonateBloodActionPerformed

    private void bSellBloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSellBloodActionPerformed
        SellBloodForm sell = new SellBloodForm();
        sell.setVisible(true);
    }//GEN-LAST:event_bSellBloodActionPerformed

    private void bRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRefreshActionPerformed
        initiateComponents();
    }//GEN-LAST:event_bRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DonorsMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DonorsMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DonorsMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DonorsMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new DonorsMainForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel OuterPanel;
    private javax.swing.JButton bDeleteAccount;
    private javax.swing.JButton bDonateBlood;
    private javax.swing.JButton bDonateCash;
    private javax.swing.JButton bRefresh;
    private javax.swing.JButton bRemindMe;
    private javax.swing.JButton bSellBlood;
    private javax.swing.JButton bViewProfile;
    private javax.swing.JPanel buttonpanel;
    private javax.swing.JPanel innerPanel;
    private javax.swing.JLabel lLastBloodDonation;
    private javax.swing.JLabel lNextBloodDonation;
    private javax.swing.JLabel lRegisteredWith;
    private javax.swing.JLabel lWarning;
    private javax.swing.JLabel lWelcome;
    // End of variables declaration//GEN-END:variables

    private String getNextDate() {
        int year;
        int month;
        int nextMonth;
        year = Integer.parseInt(splitDate[0]);
        month = Integer.parseInt(splitDate[1]);
        nextMonth = month + 3;
        if (nextMonth > 11) {
            year++;
            nextMonth = nextMonth - 12;
        }
        nextDonation = Integer.toString(year) + "-" + Integer.toString(nextMonth) + "-" + splitDate[2];
        return nextDonation;
    }
}
